# Generated by Django 3.2.5 on 2024-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_website', '0002_project_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
