# Generated by Django 3.2.5 on 2024-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_website', '0003_screenshot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default="Project's subtitle", max_length=120),
        ),
    ]
