# Generated by Django 3.2.5 on 2024-11-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_website', '0004_project_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='projects', to='work_website.Feature'),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='projects', to='work_website.Objectives'),
        ),
        migrations.AddField(
            model_name='project',
            name='technos',
            field=models.ManyToManyField(blank=True, related_name='projects', to='work_website.Techno'),
        ),
    ]
