name: Django CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Build Docker images
      - name: Build Docker images
        run: |
          docker buildx build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} -t edwin350/website:latest -f Dockerfile . --progress=plain

      # Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push to Docker Hub
      - name: Push Docker images
        run: |
          docker push edwin350/website:latest

      # deploy
      # - name: Deploy to Render
      #   env:
      #     RENDER_WEBHOOK: ${{ secrets.RENDER_DEPLOY_WEBHOOK }}
      #   run: |
      #     curl -X POST "${RENDER_WEBHOOK}"